version: '3.5'
services:
    mysql_common:
        container_name: mysql_common
        image: mysql:latest
        restart: on-failure
        environment:
            MYSQL_DATABASE: common_application
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
          - 3301:3306
        volumes:
          - ./docker/volumes/mysql/data:/var/lib/mysql
    php_common:
        container_name: php_common
        build: ./docker/build/php
        tty: true
        depends_on:
            - mysql_common
        volumes:
          - .:/var/www/common-application
    nginx_common:
        container_name: nginx_common
        image: nginx:latest
        restart: on-failure
        ports:
          - 8000:80
        volumes:
          - ./:/var/www/common-application
          - ./docker/build/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - php_common
          - mysql_common